"""add notification_score_threshold to profiles

Revision ID: 183219bc0847
Revises: 013d7c758a99
Create Date: 2026-07-30 18:58:12.908228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '183219bc0847'
down_revision: Union[str, Sequence[str], None] = '013d7c758a99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('notification_score_threshold', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'notification_score_threshold')
    # ### end Alembic commands ###
