"""add auth fields to users (password_hash, is_admin, is_active)

Revision ID: 471e9b5a5fe6
Revises: da4baa756e6d
Create Date: 2026-07-30 22:50:18.712418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '471e9b5a5fe6'
down_revision: Union[str, Sequence[str], None] = 'da4baa756e6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column(
        'users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.add_column(
        'users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
