"""add employment_types and requires_brazil_eligible to profiles

Revision ID: da4baa756e6d
Revises: 183219bc0847
Create Date: 2026-07-30 22:34:58.058780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da4baa756e6d'
down_revision: Union[str, Sequence[str], None] = '183219bc0847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('employment_types', sa.JSON(), nullable=False))
    op.add_column('profiles', sa.Column('requires_brazil_eligible', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'requires_brazil_eligible')
    op.drop_column('profiles', 'employment_types')
    # ### end Alembic commands ###
